# Generated by Django 3.2 on 2022-11-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(1, 'User'), (2, 'Shipper'), (3, 'Admin')], default=0)),
                ('token_device', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'Account',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_notes', models.CharField(max_length=255)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='api_account.location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_account.account')),
                ('name', models.CharField(default='User', max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('distance_view', models.IntegerField(default=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='api_account.address')),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_account.account')),
                ('name', models.CharField(default='User', max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'Female')], default=0)),
                ('url_identification_top', models.CharField(max_length=255, null=True)),
                ('url_identification_back', models.CharField(max_length=255, null=True)),
                ('identification_info', models.CharField(blank=True, max_length=500, null=True)),
                ('url_face_video', models.CharField(max_length=255, null=True)),
                ('confirmed', models.IntegerField(choices=[(0, 'UnConfirm'), (1, 'Confirming'), (2, 'Confirmed'), (-1, 'Deny')], default=0)),
                ('distance_receive', models.IntegerField(default=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_account.address')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_account.location')),
            ],
        ),
    ]
