# Generated by Django 3.2 on 2022-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
