# Generated by Django 3.2 on 2022-11-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0002_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_account.address'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_account.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='api_account.address'),
        ),
    ]
